FROM  node:14.16.0-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm install -g serve

ENV REACT_APP_BACKEND_URL="http://localhost:8080/"

RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]