version: "3.5"

services:
  frontend:
    image: 1-14-frontend
    ports:
      - 4567:5000
  backend:
    image: 1-14-backend
    ports:
      - 4568:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres_db
  redis:
    image: redis:latest
    ports:
      - 6379