version: "3.5"

services:
  frontend:
    image: 1-14-frontend
    environment:
      - VIRTUAL_HOST=http://127.0.0.1:80
    ports:
      - 5000
  backend:
    image: 1-14-backend
    ports:
      - 4568:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres_db
  redis:
    image: redis:latest
    ports:
      - 6379
  proxy:
    image: ninanung/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on:
      - backend