version: "3.5"

services:
  frontend:
    image: frontend
    ports:
      - 4567:5000
  backend:
    image: backend
    ports:
      - 4568:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: postgres_db
    volumes:
      - ./pg_database:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379

